baseURL = "/"


[params]
primaryColor = "#282c37"
secondaryColor = "#d9e1e8"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = ""
  weight = 1
  languageCode = "en-us"
  title = "Doc List"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "CBB Stats Help"
  copyright = "Dadgum Box Scores | Chris Gallo © 2017-2019."

    # navigation
    [Languages.en.menu]
    
          [[Languages.en.menu.main]]
        weight = 2
        name = "purpose"
        url = "/about/purpose"
        
      [[Languages.en.menu.main]]
        weight = 3
        name = "contact"
        url = "/contact"
        

    # banner
    [Languages.en.params.banner]
      title = "College Basketball Stats Help"
      description = "Find what you're looking for"
      image = "images/banner.jpg"
      placeholder = "four factors, efficiency, assists, turnovers"

    # Topics
    [Languages.en.params.topics]
      title = "Find information by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Can't find what you're looking for?"
      description = "Not finding what you're after or have a suggestion on how to improve this information, drop me an email."
      btnText = "contact us"
      btnURL = "/contact"

    # contact
    [Languages.en.params.contact]
      title = "Question, Comment, or Concern?"
      content = "I might not be able to reply right away or at all, but I'll read every single email. So if you want to send me an email, please do so here: <a href='cbbstatshelp@gmail.com'>cbbstatshelpgmail.com</a>."
